/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtualpet;

import java.util.Scanner;

public class App {
    
    public static int firstPrompt(Scanner scanner, VirtualPet virtualPet) {
                System.out.println("Jake the Dog");
               // System.out.printf("Exp: %s \n", );
                System.out.printf("Hunger: %s \n", virtualPet.getHunger());
                System.out.printf("Thirst: %s \n", virtualPet.getThirst());
              //  System.out.println("Boredom:");
                System.out.printf("Tiredness: %s \n", virtualPet.getTiredness());
              //  System.out.println("Waste:");
              //  System.out.println("Sickness:");

                System.out.println("\n What do you want to do?");
                System.out.println("1. Feed ");
                System.out.println("2. Give Jake water");
                System.out.println("3. Put Jake to sleep");
                System.out.println("4. Quit playing with Jake");
                // System.out.println("5. Take Jake for a walk");
                // System.out.println("6. Give Jake some medicine");
                System.out.println("Enter your choice(1-6): ");

                return scanner.nextInt();
    }

    public static void main(String[] args) {
        //Interact with a VirtualPet object in this method
        VirtualPet virtualPet = new VirtualPet();
        Scanner scanner = new Scanner(System.in);
            while (true){
                
                int choice = firstPrompt(scanner, virtualPet);

                switch (choice) {
                    case 1:
                        virtualPet.feed();
                        System.out.println("You fed Jake.");
                        break;
                    case 2:
                        virtualPet.water();
                        System.out.println("You gave Jake some water.");
                        break;

                    // case 3:
                    //     virtualpet.play();
                    //     System.out.println("You played with Jake.");
                    //     break;
                    case 3:
                        virtualPet.sleep();
                        System.out.println("You put Jake to sleep.");
                        break;
                    // case 5:
                    //     virtualpet.takeJakeForAWalk();
                    //     System.out.println("You walked Jake.");
                    //     break;
                    // case 6:
                    //     virtualpet.giveJakeSomeMedicine();
                    //     System.out.println("You gave Jake some medicine.");
                    //     break;
                    case 4:
                        System.exit(0);
                    default:
                        System.out.println("Invalid choice. Please try again.");
                }
    }
}
}
